#+title: Initialism

* Table Of Contents
:PROPERTIES:
:TOC:      :include all :ignore (this)
:END:
:CONTENTS:
- [[#justification-for-existence][Justification For Existence]]
- [[#usage][Usage]]
  - [[#building][Building]]
  - [[#reviewing][Reviewing]]
  - [[#inserting][Inserting]]
  - [[#deleting][Deleting]]
  - [[#continuing][Continuing]]
- [[#frequently-answered-questions][Frequently Answered Questions]]
  - [[#dont-handle-eol][Why don't you handle the end-of-line character]]
- [[#installation][Installation]]
  - [[#traditional][Traditional]]
  - [[#package][Package]]
    - [[#manually][Manually]]
    - [[#automatically][Automatically]]
- [[#is-it-an-initialism-acronym-or-abbreviation][Is It An Initialism, Acronym, or Abbreviation?]]
- [[#definitions][Definitions]]
:END:

* Justification For Existence

*This tool makes memorizing scripts and speaches easier!*

Why struggle with the tedious and error-prone task of creating initialisms for
an entire script by hand? This program does it with impeccable precision for you
every time, allowing you to format the output to your liking. Experience the
ease and convenience for yourself―your brain will love it!

- Before using this program
  - Watch [[https://www.youtube.com/watch?v=Jbe1-oHnR6k][Lauren Tothero]] explain how this technique works

* Usage

In this example create the initialism =EMACS= from the phrase "Eventually
Munches All Computer Storage" following the most frequently used functions in
order of the typical workflow.

- Building it
- Reviewing it
- Inserting it
- Deleting it

** Building

Start by positioning the Cursor at the start of the first word. Call
~initialism-dispatch~. Notice that the value of the initialism appears in the
Echo Area, and the Cursor moves one step forward. Call ~initialism-dispatch~
again, and the Cursor moves, but nothing appears in the Echo Area. You can't make
an initialism using whitespace characters, so it is ignored. Call
~initialism-dispatch~ noting that the current initialism value is again
displayed in the Echo Area, and the Cursor moves forward, this time with an
additional character appended. Call
~initialism-dispatch~, and the space character is then ignored. As you repeatedly
call ~initialism-dispatch~, you can watch the initialism built until you finally
reach the end of the line, and I don't know how to proceed.

/@ represents the cursor location before calling ~initialism-dispatch~/

#+begin_src text
@Eventually Munches All Computer Storage
(E)
Eventually @Munches All Computer Storage
(EM)
Eventually Munches @All Computer Storage
(EMA)
Eventually Munches All @Computer Storage
(EMAC)
Eventually Munches All Computer @Storage
(EMACS)
#+end_src

Wondering why [[Why don't you handle the end-of-line character][I don't handle end-of-lines?]]

** Reviewing

Review the initialism value by calling ~C-u initialism-dispatch~ and noting in
the Echo Area.

#+begin_src text
(EMACS)
#+end_src

** Inserting

Insert the initialism value by calling ~C-u C-u initialism-dispatch~.

#+begin_src text
/@\
/(EMACS)@\
#+end_src

It's important to understand that the format of the initialism is separate from
the data itself. The actual initialism data, the /Model/, is stored in a private
variable that you won't need to touch. What you see presented from that data,
the /View/, is the result of formatting the /Model/ with the
~initialism-format-string~, which you can modify to your liking.

Consider this example so far.

- The /Model/: EMACS
- The /View/: (EMACS)

Imagine that you want to format the initialism as bold text in LaTeX without
parentheses around it. Use ~customize~ to customize ~initialism-format-string~
with the value =\textbf{%s}= and you now end up with

- The /Model/: EMACS
- The /View/: =\textbf{EMACS}=

/Note: if you need the model's value then call ~initialism-get-model~/

** Deleting

Delete the initialism value by calling ~C-u C-u C-u initialism-dispatch~ and
note in the Echo Area the message.

#+begin_src text
(initialism) View deleted.
#+end_src

** Continuing

This example reflects the typical workflow for building an initialism. Call
~initialism-help~ to review the workflow. If you want to call the individual
functions for each workflow step, you'll also find their names.

Whenever I work, I try to explain what I'm doing in the Echo Area. If something
doesn't work right, start there, and if I failed you, please create a support
ticket.

Now, start creating your next initialism.

* Frequently Answered Questions
*** Why don't you handle the end-of-line character

Indeed, now you must ask yourself, "But why cant you handle the end-of-line
character, my dear system?" The answer is simple: it makes it easy for you to
create initialism starting from wherever you like, skipping lines, paragraphs,
or whatever you wish; there are no limits on the source and sequencing of your
initialism. Therefore, I assume nothing beyond the fact that initialism is built
using only the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Char-Classes.html#Char-Classes][Character Classes]] =[[:alnum:]]= and =[[:punct:]]=

* Installation

** Traditional

Download =initialism.el= into =~/src= and add this to your configuration file:

#+begin_src emacs-lisp
(add-to-list 'load-path "~/src")
(require 'initialism)
#+end_src

** Package
*** Manually

Download =initialism.el=, call ~package-install-file~, and specify that file.

Add ~(require 'initialism)~ to your configuration file.

*** Automatically

Eventually this will get added to [[https://melpa.org/#/][MELPA]].

* Is It An Initialism, Acronym, or Abbreviation?

- What is the difference between an acronym and an initialism?
  - Both acronyms and initialisms are made up of the first letter or letters
    of the words in a phrase. The word /acronym/ typically applies when the
    resulting thing can be read as a word; for example, /radar/ comes from
    "𝙧𝙖dio 𝙙etection 𝙖nd 𝙧anging" and /scuba/ comes from
    "𝙨elf-𝙘ontained 𝙪nderwater 𝙗reathing 𝙖pparatus." The word
    /initialism/ only applies when the resulting thing is read as an
    abbreviation; for example /DIY/, which comes from "𝙙o 𝙞t
    𝙮ourself," is pronounced by saying the names of the letters. Note that
    the word /acronym/ is also sometimes used to mean "initialism."
- What is the difference between an acronym and an abbreviation?
  - An acronym is a kind of abbreviation. Abbreviations can be shortened
    forms of any kind. For example, /appt/ is an abbreviation of
    /appointment/, and /ASAP/ is an abbreviation of 𝙖s 𝙨oon 𝙖s 𝙥ossible.
    /ASAP/, however, also qualifies as an acronym because it is made up of
    the initial letters of the phrase it comes from: 𝙖s 𝙨oon 𝙖s 𝙥ossible.
- Source: "Acronym. (Frequently Asked Questions)" Merriam-Webster.com
  Dictionary, Merriam-Webster,
  https://www.merriam-webster.com/dictionary/acronym. Accessed 19 Apr. 2024.

* Definitions

- initialism :: :an abbreviation formed from initial letters
  - Source: "Initialism." Merriam-Webster.com Dictionary, Merriam-Webster,
    https://www.merriam-webster.com/dictionary/initialism. Accessed 19
    Apr. 2024.
- acronym :: :a word (such as /NATO/, /radar/, or /laser/) formed from the
  initial letter or letters of each of the successive parts or major parts of a
  compound term
  - /also/ :an abbreviation (such as FBI) formed from initial letters:
    initialism
    - Is OK an acronym?
      - /OK/ is technically an acronym. It comes from the phrase "oll korrect," a
        humorous alteration of "all correct."
  - Examples of acronym in a Sentence
    - The North Atlantic Treaty Organization is known by the /acronym/ "NATO."
  - Source: "Acronym." Merriam-Webster.com Dictionary, Merriam-Webster,
    https://www.merriam-webster.com/dictionary/acronym. Accessed 19 Apr. 2024.
- abbreviation :: :a shortened form of a written word or phrase used in place of
  the whole word or phrase
  - "Amt" is an /abbreviation/ for "amount."
  - "USA" is an /abbreviation/ of "United States of America."
  - Did you know?
    - What's the difference between an /abbreviation/ and an /acronym/?
      - Some people are unsure of whether to call /ASAP/ or /appt/ abbreviations or
        acronyms. Both /abbreviation/ and /acronym/ are used to refer to a shortened
        form, but an acronym is a shortened form of a phrase and is usually made
        up of the initial letters of that phrase. For example, /NATO/ comes from
        "North Atlantic Treaty Organization," and /ASAP/ comes from "as soon as
        possible." Abbreviations, on the other hand, can be shortened forms of
        words or phrases, and need not necessarily be made up of the initial
        letters of either. /ASAP/ and /appt/ (for /appointment/) are both considered
        abbreviations, but only /ASAP/ is an acronym. Acronyms are a type of
        abbreviation.
  - Source: "Abbreviation." Merriam-Webster.com Dictionary, Merriam-Webster,
    https://www.merriam-webster.com/dictionary/abbreviation. Accessed 19
    Apr. 2024.
